config/routes.rb
Rails.application.routes.draw do
  resources :projects
  get 'static_pages/index'
  get 'static_pages/close_details'

   root 'static_pages#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  mount_uploader :img, PictureUploader
  mount_uploader :thumb, ThumbUploader 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :img, :description, :thumb)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @projects = Project.all

    @project = Project.find(params[:id]) if (params.has_key?(:id))

    respond_to do |format|
      format.html
      format.js
    end
  end

  def close_details
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PortfolioRailsJl</title>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/icon?family=Material+Icons', 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <!-- ///////////////////////////Start navbar///////////////////////// -->
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo center">Portfolio</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="sass.html"></a></li>
          <li><a href="badges.html"></a></li>
          <li><a href="collapsible.html"></a></li>
        </ul>
      </div>
    </nav>
    <!-- /////////////////////////end navbar///////////////////// -->
  </header>

<%= yield %>


</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :img %><br>
    <%= f.text_field :img %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :thumb %><br>
    <%= f.text_field :thumb %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Img</th>
      <th>Description</th>
      <th>Thumb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.img %></td>
        <td><%= project.description %></td>
        <td><%= project.thumb %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Img:</strong>
  <%= @project.img %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Thumb:</strong>
  <%= @project.thumb %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/static_pages/_details.html.erb
<div class='col s8'>
  <%= image_tag(@project.img.url(), class: "responsive-img") %>
</div>
<div class="col s4">
  <%= "<h2 class=\"white-text\">#{@project.title}</h2>".html_safe %>
  <%= "#{@project.description}".html_safe %>
  <%= link_to @project.url, target: '_blank', class: 'waves-effect waves-light btn' do %>
    <i class="fa fa-github-alt left"></i> Repository
  <% end %>
  <%= link_to static_pages_close_details_path, remote: true, class: 'waves-effect waves-light btn right' do %>
    <i class="material-icons left">close</i> Close
  <% end %>
</div>

app/views/static_pages/close_details.js.erb
$('#details').html('')
<%= yield %>

app/views/static_pages/index.html.erb
<main>
  <!-- /////////////////////////Start Panel//////////////////////// -->
<div class="row">
  <div class="col s12">
    <div id="panel" class="card-panel card medium">
      <div class="bloc">
        <img class="responsive-img" src="images/travaux-2.jpg" alt="">
        <br>
        <h4 class="white-text">Jade Lemaissi</h4>
        <p class="white-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="bloc">
        <img class="responsive-img" src="images/travaux-2.jpg" alt="">
        <br>
        <h4 class="white-text">Compétences</h4>
        <p class="white-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="bloc">
        <%= image_tag "images/travaux-2.jpg", alt: '', class: 'responsive-img' %>
        <br>
        <h4 class="white-text">Formation</h4>
        <p class="white-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>
  </div>
</div>
<!-- /////////////////////////end Panel//////////////////////// -->
<div class="row">
  <% @projects.each do |p| %>
    <%= link_to static_pages_index_path(id: "#{p.id}"), remote: true do %>
      <div class="col s6 m3">
        <%= image_tag(p.thumb.url(), class: "responsive-img", alt: '') %>
        <%= "<p><strong>#{p.title}</strong></p>".html_safe %>
      </div>
    <% end %>
  <% end %>
</div>
<div id="details" class="row"></div>
  <!-- ///////////////////start  panel downloadable////////////////// -->
    <div class="row">
      <div class="col s4">
        <!-- <div class="card-panel card small"> -->
          <a href="images/cv.pdf" download>
            <img class="materialboxed responsive-img" width="250" src="images/travaux-2.jpg">
          </a>
        <!-- </div> -->
      </div>
    </div>
  <!-- ///////////////////end  panel downloadable////////////////// -->

</main>

<!-- ///////////////////////Start footer////////////////////// -->
  <footer id="findepage" class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Liens</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="http://github.com/Jade-L"><i class="fa fa-github-alt left"></i>Github</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">CodeWar</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>
<!-- ///////////////////////////////end footer////////////////////// -->

app/views/static_pages/index.js.erb
$('#details').html('<%=j render "details" %>')
<%= yield %>                                                                                      